### ISSUE TITLE
Strange distance computation for DiscreteDomain and ProdDiscreteDomain

### ISSUE THREAD

**Issue by yosipk** [dragonfly/dragonfly#24]
For all domains method `compute_distance` behaves as I'd expect, except for `DiscreteDomain`:
https://github.com/dragonfly/dragonfly/blob/master/dragonfly/exd/domains.py#L177

and `ProdDiscreteDomain`:
https://github.com/dragonfly/dragonfly/blob/master/dragonfly/exd/domains.py#L290

where it returns 1 if the elements are different and 0 if they are the same. Is that intended?

```
from dragonfly.exd.domains import DiscreteNumericDomain, DiscreteDomain, CartesianProductDomain

d1 = dragonfly.exd.domains.DiscreteNumericDomain([0.0, 1.0])
d2 = dragonfly.exd.domains.DiscreteDomain(['same', 'different'])
d = dragonfly.exd.domains.CartesianProductDomain([d1, d2])

print(d.compute_distance([0.0, 'same'], [0.0, 'same']))        # outputs 1.0, would expect 0.0
print(d.compute_distance([0.0, 'same'], [0.0, 'different']))   # outputs 0.0, would expect 1.0
print(d.compute_distance([0.0, 'same'], [1.0, 'different']))   # outputs 1.0, would expect 2.0
```

**Comment by kirthevasank** [comment]
Thanks for pointing this out - this was a bug and has been fixed in the latest commit. See example below.

This change will not be reflected in the pip install yet -- we will incorporate this along with other changes in a couple of days. For now, you can install via source following the instructions under step 2 here: https://dragonfly-opt.readthedocs.io/en/master/install/

```
>>> from dragonfly.exd.domains import DiscreteNumericDomain, DiscreteDomain, CartesianProductDomain
>>> d1 = DiscreteNumericDomain([0.0, 2.3])
>>> d2 = DiscreteDomain(['cat', 'dog'])
>>> d = CartesianProductDomain([d1, d2])
>>> d.compute_distance([0.0, 'cat'], [0.0, 'cat'])
0.0
>>> d.compute_distance([0.0, 'cat'], [0.0, 'dog'])
1.0
>>> d.compute_distance([0.0, 'cat'], [2.3, 'dog'])
3.3
```
