### ISSUE TITLE
load_config does not exist.

### ISSUE THREAD

**Issue by alelasantillan** [dragonfly/dragonfly#26]
I've tried to run the in_code_demo.py in the supernova folder and I found that the load_config  function is not available. Will it be added?

**Comment by kirthevasank** [comment]
Have you checked out the latest version of the code?
It is defined in these files,
https://github.com/dragonfly/dragonfly/blob/master/dragonfly/__init__.py
https://github.com/dragonfly/dragonfly/blob/master/dragonfly/exd/cp_domain_utils.py
