### ISSUE TITLE
Constraints do not work in code

### ISSUE THREAD

**Issue by crcollins** [dragonfly/dragonfly#28]
I took the code in examples/synthetic/hartmann6_4/in_code_demo.py
and modified it to include the simple constraint from examples/synthetic/hartmann3_constrained/config.json

I basically just added this in place of the old `config_params`:

```
constraints = {
  "constraint_1": {
      "name": "quadrant",
      "constraint": "np.linalg.norm(x[0:2]) <= 0.5"
    }
}
config_params = {'domain': domain_vars, 'fidel_space': fidel_vars,
                   'fidel_to_opt': fidel_to_opt, 'domain_constraints': constraints}
```

I get this error when I try to run it:
```
Traceback (most recent call last):
  File "in_code_demo.py", line 58, in <module>
    main()
  File "in_code_demo.py", line 39, in main
    config = load_config(config_params)
  File "/home/chris/projects/dragonfly/dragonfly/exd/cp_domain_utils.py", line 102, in load_config
    domain_constraints=domain_constraints, domain_info=domain_info, *args, **kwargs)
  File "/home/chris/projects/dragonfly/dragonfly/exd/cp_domain_utils.py", line 262, in load_domain_from_params
    cp_domain = domains.CartesianProductDomain(list_of_domains, domain_info)
  File "/home/chris/projects/dragonfly/dragonfly/exd/domains.py", line 365, in __init__
    self._constraint_eval_set_up()
  File "/home/chris/projects/dragonfly/dragonfly/exd/domains.py", line 377, in _constraint_eval_set_up
    isinstance(self.domain_constraints[idx][1], str) and
KeyError: 0
```
I assume this should work. The same constraints work when calling with dragonfly-script.

I did a bit of digging and it seems like the constraints are not getting processed when loaded with load_config.

**Comment by kirthevasank** [comment]
This has now been fixed with examples in
https://github.com/dragonfly/dragonfly/blob/master/examples/synthetic/hartmann3_constrained/in_code_demo.py
https://github.com/dragonfly/dragonfly/blob/master/examples/synthetic/park1_constrained/in_code_demo.py
https://github.com/dragonfly/dragonfly/blob/master/examples/synthetic/borehole_constrained/in_code_demo.py

**Comment by crcollins** [comment]
Looks like it works now. Thanks!
