### ISSUE TITLE
Parallel evaluation with ei 

### ISSUE THREAD

**Issue by ZhenhuaLiu2512** [dragonfly/dragonfly#31]
Hi!
 I tried to run parallel Bayesian optimization for the branin function with following options & codes:
```
options = [
                   {'name':'capital_type','default':'return_value'}, 
                   {'name':'build_new_model_every', 'default': 17}, 
                   {'name':'init_capital','default':10}, 
                   {'name':'initial_method','default':'rand'},
                   {'name':'euc_init_method','default':'latin_hc'}, 
                   {'name':'acq', 'default':'ei'},
                   {'name': 'handle_parallel', 'default': 'halluc'}, 
                   {'name': 'acq_opt_max_evals', 'default': 3}, 
                   {'name':'domain_kernel_type', 'default':'matern'}, 
                   {'name':'domain_matern_nu', 'default':2.5} 
                   ]
        options = load_options(options)
        min_val, min_pt, history = minimise_function(func, domain,opt_method='bo', max_capital =    60, options=options)
```
in which _func_ is the name of branin function and _domain_ is the list of computation domain, but the acquisition function always return the same position for evaluation, same problem also happens with _ucb_ acquisition function. 
`Evaluated inputs: [[-0.53138911  2.16230016]
 [ 8.00611623  3.71417474]
 [ 5.71641293 11.39269664]
 [ 5.1832132  14.4029029 ]
 [-2.62100231  5.23051845]
 [ 8.76691612  0.13967317]
 [ 1.67777453 12.11758913]
 [-4.62652079  9.34890705]
 [ 3.23838423  8.55028105]
 [ 0.08195912  6.08355315]
 [ 2.5         7.5       ]
 [ 6.25        3.75      ]
 [ 6.25        3.75      ]
 [ 2.5         7.5       ]
 [ 6.25        3.75      ]
 [ 2.5         3.75      ]
 [ 6.25        3.75      ]
 [ 6.25        3.75      ]
 [ 6.25        3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 6.25        3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [-1.25        3.75      ]
 [ 6.25        3.75      ]
 [-1.25       11.25      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5        11.25      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]
 [ 2.5         3.75      ]]
`
If I change the acq_opt_max_evals back to -1, or switch the acquisition function to _ts_ then everything works well:
`Evaluated inputs: [[ 6.48048264e+00  5.16685860e+00]
 [-1.20743781e-01  9.70861310e+00]
 [ 4.26112145e+00  7.47955916e+00]
 [-4.72670657e+00  7.80306038e+00]
 [ 3.07030981e+00  4.05256585e+00]
 [-1.86899555e+00  1.08101134e+01]
 [ 8.96877227e+00  1.21185092e+01]
 [-3.45598584e+00  1.09148145e+00]
 [ 2.12922567e+00  1.64593026e+00]
 [ 8.41270012e+00  1.42543831e+01]
 [ 2.90100098e+00  2.57904053e+00]
 [-4.99999999e+00  1.50000000e+01]
 [-3.59375000e+00  1.47656250e+01]
 [-4.99999821e+00  1.49999991e+01]
 [ 2.96875000e+00  2.34375000e+00]
 [-3.50889206e+00  1.27881145e+01]
 [-5.00000000e+00  1.50000000e+01]
 [ 2.94311523e+00  2.12219238e+00]
 [ 2.99827576e+00  2.81227112e+00]
 [ 3.17812009e+00  1.87500000e+00]
 [ 2.86293507e+00  2.60182142e+00]
 [ 2.92676700e+00  2.69622803e+00]
 [-1.25000000e+00  3.75000000e+00]
 [ 6.25000000e+00  3.75000000e+00]
 [ 6.25000000e+00  3.75000000e+00]
 [ 9.53125000e+00  3.28125000e+00]
 [-1.25000000e+00  1.12500000e+01]
 [ 2.50000000e+00  3.75000000e+00]
 [ 6.25000000e+00  1.03125000e+01]
 [ 1.00000000e+01  9.32647705e+00]
 [-3.30993652e+00  1.12481689e+01]
 [-1.25000000e+00  1.03125000e+01]
 [ 2.50000000e+00  8.57666016e+00]
 [-4.91210938e+00  1.06201172e+01]
 [-4.27455902e+00  1.06264114e+01]
 [-3.12500000e+00  1.31250000e+01]
 [ 2.50000000e+00  5.62500000e+00]
 [-3.45642112e+00  1.40625002e+01]
 [-2.10847855e-01  6.19105339e+00]
 [-2.10876493e-01  6.19166850e+00]
 [ 9.98535156e+00  7.49267578e+00]
 [-3.45626198e+00  1.40625002e+01]]
`
 Could anyone help me about this issue?  Did I miss anything for parallel evaluation?

**Comment by kirthevasank** [comment]
Two issues going on here.
First, the problem you are seeing above is because you have set acq_opt_max_evals to 3. In 3 evals, it cannot really maximise the acquisition. We would recommend setting this to the default value (-1) or set it to be a large value (e.g. 1000).

Second, you are not really running parallel BO here. You should look at the example in https://github.com/dragonfly/dragonfly/blob/master/examples/nas/demo_nas.py

**Comment by ZhenhuaLiu2512** [comment]
Works now! Many thanks!
