### ISSUE TITLE
Too much time spent in isolated iteration

### ISSUE THREAD

**Issue by alelasantillan** [dragonfly/dragonfly#38]
I was measuring the time spent in each iteration of minimise_function and I've noticed that in my laptop it takes less than a second most of the time, but sometimes an iteration 
takes an enormous amount of time. For example this:

myfunction_spent_time: 3
init dragonfly after computing the function:
Thu Apr 25 18:18:35 EDT 2019
final dragonfly after computing the function:
Thu Apr 25 18:27:19 EDT 2019

Almost 10 minutes. This is weird. Any idea where the time is being consumed?
Is there any way to limit the execution time to some maximum amount of time?

**Comment by kirthevasank** [comment]
This is probably due to hyperparameter tuning of the GP which happens every 17 iterations by default.

If your function evaluations are generally cheap, you could use some of the other methods besides BO instead. See https://dragonfly-opt.readthedocs.io/en/master/doc_main_apis/

**Comment by alelasantillan** [comment]
Kithevasank, you are right. The delays are every 17 iterations. I should give a try to other methods.
Thank you!
