### ISSUE TITLE
installing dragonfly under pypy fails

### ISSUE THREAD

**Issue by alelasantillan** [dragonfly/dragonfly#42]
I've tried to accelerate the dragonfly execution by using pypy, which is a python environment way faster than traditional python.

The problem it has is compatibility and that is precise the case with dragonfly.

Any idea if dragonfly will be supported under pypy at any time?

**Comment by crcollins** [comment]
Could you list the errors that you are seeing? I just tried a quick install of Dragonfly with PyPy. While there was an error that came up in the install, it appears to still run. The error seems to be the same flavor as the errors that were appearing when trying to install numpy/scipy so I assume it is a PyPy pip issue.

Here is the error that I hit on the install:
```
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
    File "/tmp/pip-build-ftZDIM/dragonfly-opt/setup.py", line 84, in <module>
      **setup_options
    File "/home/chris/projects/test/envpypy/site-packages/numpy/distutils/core.py", line 171, in setup
      return old_setup(**new_attr)
    File "/usr/lib/pypy/lib-python/2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/chris/projects/test/envpypy/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/chris/projects/test/envpypy/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/chris/projects/test/envpypy/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for dragonfly-opt
Failed to build dragonfly-opt
```

And here is running Dragonfly with PyPy after the install:
```
(envpypy)chris@chris-desktop:~/projects/test$ pypy
Python 2.7.13 (7.0.0+dfsg-1~ppa1~ubuntu16.04, Feb 07 2019, 20:56:09)
[PyPy 7.0.0 with GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from dragonfly import minimise_function
>>>> min_val, min_pt, history = minimise_function(lambda x: x ** 4 - x**2 + 0.1 * x, [[-10, 10]], 10)
Optimisation with bo(ei-ucb-ttei-ts-add_ucb) using capital 10.0 (return_value)
Capital spent on initialisation: 5.0000(0.5000).
Legend: <iteration_number> (<num_successful_queries>) cap=<fraction_of_capital_spent>:: curr_max=<current_maximum_value>, acqs=<num_times_each_acquisition_was_used>
#012 (011, 1.100):: curr_max=0.17375, acqs=[ei:0, ucb:1, ttei:0, ts:0, add_ucb:5], 
>>>> min_val, min_pt
(-0.1737546597619392, array([0.61542109]))
```

**Comment by alelasantillan** [comment]
My case was different, I was able to install it without errors after trying each and every way explained here:
 https://dragonfly-opt.readthedocs.io/en/master/install/
 but then it failed in the import part:
>>> from dragonfly import minimise_function 

Can you post the command you executed to install it? In the end your install was successful!

**Comment by crcollins** [comment]
Sure, I ran this. I think some of the steps could be joined together, but this is exactly what I ran for the test install.
```
mkdir test
cd test
virtualenv envpypy -p pypy
. envpypy/bin/activate
pypy -m pip install numpy
pypy -m pip install scipy future six
pypy -m pip install dragonfly-opt
pypy
...
```

What error did you get for the import?

**Comment by alelasantillan** [comment]
>>What error did you get for the import?
I added the error in my previous comment. Unfortunatelly I followed exactly what you did and the error is the same
This is the last part:
ImportError: dlopen(/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_con_pypy3_6_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy3-71-darwin.so, 6): Symbol not found: _cbbcsd_
  Referenced from: /Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_con_pypy3_6_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy3-71-darwin.so
  Expected in: flat namespace
 in /Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_con_pypy3_6_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy3-71-darwin.so

Maybe we have different pypy versions

**Comment by alelasantillan** [comment]
This is what I have in my pypy virtenv:
(virtualenv_con_pypy3_6_7_1_0) Alejandro:backtest10 alejandrosantillaniturres$ pip freeze
cffi==1.12.2
cycler==0.10.0
Cython==0.29.7
dragonfly-opt==0.1.2
future==0.17.1
greenlet==0.4.13
kiwisolver==1.1.0
matplotlib==3.0.3
numpy==1.16.1
pandas==0.24.2
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
readline==6.2.4.1
scipy==1.2.1
six==1.12.0

**Comment by crcollins** [comment]
That appears to be some issue with your scipy install. I am trying to setup a env with the versions you are using now.

**Comment by alelasantillan** [comment]
As I can see, you have Python 2.7.13 in your pypy. I think that is the main difference.

**Comment by alelasantillan** [comment]
Unfortunately it failled also in my pypy2.7 install:

$ MACOSX_DEPLOYMENT_TARGET=10.14 pip install dragonfly-opt
DEPRECATION: A future version of pip will drop support for Python 2.7.
Collecting dragonfly-opt
  Using cached https://files.pythonhosted.org/packages/e4/84/4862e7a30a99227b8d46ab0d31c1c213737682caf76b7db88191ff483824/dragonfly-opt-0.1.2.tar.gz
Requirement already satisfied: future in ./site-packages (from dragonfly-opt) (0.17.1)
Requirement already satisfied: numpy in ./site-packages (from dragonfly-opt) (1.16.3)
Requirement already satisfied: scipy in ./site-packages (from dragonfly-opt) (1.2.1)
Requirement already satisfied: six in ./site-packages (from dragonfly-opt) (1.12.0)
Building wheels for collected packages: dragonfly-opt
  Building wheel for dragonfly-opt (setup.py) ... done
  Stored in directory: /Users/alejandrosantillaniturres/Library/Caches/pip/wheels/2d/d0/c5/39976d88e4810f8d7eade081734ffc87f4bccb38aba9b3ecc7
Successfully built dragonfly-opt
Installing collected packages: dragonfly-opt
Successfully installed dragonfly-opt-0.1.2


$ pypy
Python 2.7.13 (990cef41fe11, Mar 21 2019, 12:15:10)
[PyPy 7.1.0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> from dragonfly import minimise_function
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/dragonfly/__init__.py", line 16, in <module>
    from .apis.opt import maximise_function, minimise_function, \
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/dragonfly/apis/opt.py", line 11, in <module>
    from .api_utils import preprocess_multifidelity_arguments, preprocess_arguments, \
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/dragonfly/apis/api_utils.py", line 13, in <module>
    from ..exd.cp_domain_utils import load_config_file, \
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/dragonfly/exd/cp_domain_utils.py", line 16, in <module>
    from . import domains
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/dragonfly/exd/domains.py", line 11, in <module>
    from scipy.spatial.distance import cdist
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._spherical_voronoi import SphericalVoronoi
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/spatial/_spherical_voronoi.py", line 18, in <module>
    from scipy.spatial.distance import pdist
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/spatial/distance.py", line 125, in <module>
    from ..linalg import norm
  File "/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/linalg/__init__.py", line 207, in <module>
    from ._decomp_update import *
  File "_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update
ImportError: unable to load extension module '/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy-41.so': dlopen(/Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy-41.so, 6): Symbol not found: _cbbcsd_
  Referenced from: /Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy-41.so
  Expected in: flat namespace
 in /Users/alejandrosantillaniturres/Desktop/programming/python/virtualenv_with_pypy_2_7_7_1_0/site-packages/scipy/linalg/cython_lapack.pypy-41.so


Maybe because I am in a mac?

**Comment by crcollins** [comment]
In setting this up, I ran into a lot of issues with versions of different libraries. This stuff seems like a minefield to me. So, I would be hesitant to say that this will be fully supported. In principle, I don't think there is any reason why it shouldn't "just work" with PyPy, given the correct libraries setup.

Anyway, here is what I did to get it running (this assumes you have a working virtualenv with pypy3, that was a bit of fun on its own):

```
pypy -m ensurepip
pypy -m pip install cython future six
pypy -m pip install wheel pip setuptools
pypy -m pip install numpy==1.16.1
pypy -m pip install scipy==1.2.1
pypy -m pip install cython future six scipy
pypy -m pip install dragonfly-opt

(someenv3) chris@chris-desktop:~/projects/test$ pypy3
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
/home/chris/projects/test/someenv3/lib-python/3/site.py:703: UserWarning: readline.read_init_file() not implemented
  readline.read_init_file()
And now for something completely different: ``PyPy and CPython: they are mortal
enemies intent on killing each other''
>>>> from dragonfly import minimise_function
>>>> min_val, min_pt, history = minimise_function(lambda x: x ** 4 - x**2 + 0.1 * x, [[-10, 10]], 10)
Optimisation with bo(ei-ucb-ttei-ts-add_ucb) using capital 10.0 (return_value)
Capital spent on initialisation: 5.0000(0.5000).
Legend: <iteration_number> (<num_successful_queries>) cap=<fraction_of_capital_spent>:: curr_max=<current_maximum_value>, acqs=<num_times_each_acquisition_was_used>

#012 (011, 1.100):: curr_max=0.29939, acqs=[ei:0, ucb:1, ttei:1, ts:1, add_ucb:3], 
>>>> min_val, min_pt
(-0.29938949696304024, array([-0.82597205]))
```

Again, it seems to be very temperamental with the libraries used. I would guess OSX might factor in as well.

**Comment by alelasantillan** [comment]
I will try to replicate your installation tomorrow. It's late now. Thank you very much crcollins!

**Comment by crcollins** [comment]
Maybe to cut to the chase of your actual request though, I did some very unscientific tests to see if Dragonfly was faster with PyPy, and it seemed to actually run quite a bit slower (~3x). I guess your mileage may vary.

**Comment by alelasantillan** [comment]
Well, this result closes the pypy trial. Thank you!!!

**Comment by crcollins** [comment]
You may still want to test it. It very well could have been due to poor optimization in the compilations of the libraries that I used. Numerical things like this can be highly variable.
